### ISSUE TITLE
mlflow docker settings

### ISSUE THREAD

**Issue by upura** [upura/ayniy#76]

**Comment by ryosukehata** [comment]
情報だけで申し訳ないのですが、

```
  mlflow:
    build: .
    volumes:
      - $PWD/experiments:/working/experiments
    working_dir: /working
    ports:
      - 5000:5000
    environment:
      - PYTHONPATH=/working
    command: run mlflow server --host 0.0.0.0 --port 5000
```

こんな感じでdocker-composeの中に書くと自分が作ったレポジトリでは上手く動きました。

aynjyではどのように使おうとしているのか、まだ読めなかったので情報だけ共有しておきます。
